# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: converter.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onverter.proto\x12\tconverter\"Q\n\x0e\x43onvertRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12\x16\n\x0ereturn_content\x18\x03 \x01(\x08\"h\n\x0f\x43onvertResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x18\n\x10markdown_content\x18\x03 \x01(\t\x12\x13\n\x0boutput_path\x18\x04 \x01(\t2Z\n\x10\x44oclingConverter\x12\x46\n\x0b\x43onvertFile\x12\x19.converter.ConvertRequest\x1a\x1a.converter.ConvertResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'converter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONVERTREQUEST']._serialized_start=30
  _globals['_CONVERTREQUEST']._serialized_end=111
  _globals['_CONVERTRESPONSE']._serialized_start=113
  _globals['_CONVERTRESPONSE']._serialized_end=217
  _globals['_DOCLINGCONVERTER']._serialized_start=219
  _globals['_DOCLINGCONVERTER']._serialized_end=309
# @@protoc_insertion_point(module_scope)
