# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chunker.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchunker.proto\x12\x07\x63hunker\"e\n\x0c\x43hunkRequest\x12\x13\n\tfile_path\x18\x01 \x01(\tH\x00\x12\x11\n\x07\x63ontent\x18\x02 \x01(\tH\x00\x12\x12\n\nchunk_size\x18\x03 \x01(\x05\x12\x0f\n\x07overlap\x18\x04 \x01(\x05\x42\x08\n\x06source\"\x92\x01\n\x05\x43hunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05\x12.\n\x08metadata\x18\x04 \x03(\x0b\x32\x1c.chunker.Chunk.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x44\n\x0e\x43hunkerService\x12\x32\n\x07\x43hunkIt\x12\x15.chunker.ChunkRequest\x1a\x0e.chunker.Chunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chunker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHUNK_METADATAENTRY']._options = None
  _globals['_CHUNK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CHUNKREQUEST']._serialized_start=26
  _globals['_CHUNKREQUEST']._serialized_end=127
  _globals['_CHUNK']._serialized_start=130
  _globals['_CHUNK']._serialized_end=276
  _globals['_CHUNK_METADATAENTRY']._serialized_start=229
  _globals['_CHUNK_METADATAENTRY']._serialized_end=276
  _globals['_CHUNKERSERVICE']._serialized_start=278
  _globals['_CHUNKERSERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
