# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chunker_pb2 as chunker__pb2


class ChunkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChunkIt = channel.unary_stream(
                '/chunker.ChunkerService/ChunkIt',
                request_serializer=chunker__pb2.ChunkRequest.SerializeToString,
                response_deserializer=chunker__pb2.Chunk.FromString,
                )


class ChunkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChunkIt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChunkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChunkIt': grpc.unary_stream_rpc_method_handler(
                    servicer.ChunkIt,
                    request_deserializer=chunker__pb2.ChunkRequest.FromString,
                    response_serializer=chunker__pb2.Chunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chunker.ChunkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChunkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChunkIt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chunker.ChunkerService/ChunkIt',
            chunker__pb2.ChunkRequest.SerializeToString,
            chunker__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
