# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import embedder_pb2 as embedder__pb2


class EmbedderServiceStub(object):
    """The embedder service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmbedding = channel.unary_unary(
                '/embedder.EmbedderService/GetEmbedding',
                request_serializer=embedder__pb2.TextChunk.SerializeToString,
                response_deserializer=embedder__pb2.EmbeddingVector.FromString,
                )
        self.GetEmbeddings = channel.unary_unary(
                '/embedder.EmbedderService/GetEmbeddings',
                request_serializer=embedder__pb2.TextChunks.SerializeToString,
                response_deserializer=embedder__pb2.EmbeddingVectors.FromString,
                )


class EmbedderServiceServicer(object):
    """The embedder service definition.
    """

    def GetEmbedding(self, request, context):
        """Sends a text chunk and returns an embedding vector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbeddings(self, request, context):
        """Sends multiple text chunks and returns multiple embedding vectors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbedderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=embedder__pb2.TextChunk.FromString,
                    response_serializer=embedder__pb2.EmbeddingVector.SerializeToString,
            ),
            'GetEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbeddings,
                    request_deserializer=embedder__pb2.TextChunks.FromString,
                    response_serializer=embedder__pb2.EmbeddingVectors.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedder.EmbedderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbedderService(object):
    """The embedder service definition.
    """

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedder.EmbedderService/GetEmbedding',
            embedder__pb2.TextChunk.SerializeToString,
            embedder__pb2.EmbeddingVector.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedder.EmbedderService/GetEmbeddings',
            embedder__pb2.TextChunks.SerializeToString,
            embedder__pb2.EmbeddingVectors.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
