# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import indexer_pb2 as indexer__pb2


class IndexerServiceStub(object):
    """Сервис индексации
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexDocument = channel.stream_unary(
                '/indexer.IndexerService/IndexDocument',
                request_serializer=indexer__pb2.IndexFileRequest.SerializeToString,
                response_deserializer=indexer__pb2.IndexResponse.FromString,
                )


class IndexerServiceServicer(object):
    """Сервис индексации
    """

    def IndexDocument(self, request_iterator, context):
        """Индексирует документ через streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexDocument': grpc.stream_unary_rpc_method_handler(
                    servicer.IndexDocument,
                    request_deserializer=indexer__pb2.IndexFileRequest.FromString,
                    response_serializer=indexer__pb2.IndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'indexer.IndexerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IndexerService(object):
    """Сервис индексации
    """

    @staticmethod
    def IndexDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/indexer.IndexerService/IndexDocument',
            indexer__pb2.IndexFileRequest.SerializeToString,
            indexer__pb2.IndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
