# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indexer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rindexer.proto\x12\x07indexer\"R\n\x10IndexFileRequest\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x13.indexer.FileHeaderH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\"\x98\x01\n\nFileHeader\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x33\n\x08metadata\x18\x02 \x03(\x0b\x32!.indexer.FileHeader.MetadataEntry\x12\x12\n\ntotal_size\x18\x03 \x01(\x03\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"K\n\rIndexResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10\x63hunks_processed\x18\x03 \x01(\x05\x32V\n\x0eIndexerService\x12\x44\n\rIndexDocument\x12\x19.indexer.IndexFileRequest\x1a\x16.indexer.IndexResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'indexer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEHEADER_METADATAENTRY']._options = None
  _globals['_FILEHEADER_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INDEXFILEREQUEST']._serialized_start=26
  _globals['_INDEXFILEREQUEST']._serialized_end=108
  _globals['_FILEHEADER']._serialized_start=111
  _globals['_FILEHEADER']._serialized_end=263
  _globals['_FILEHEADER_METADATAENTRY']._serialized_start=216
  _globals['_FILEHEADER_METADATAENTRY']._serialized_end=263
  _globals['_INDEXRESPONSE']._serialized_start=265
  _globals['_INDEXRESPONSE']._serialized_end=340
  _globals['_INDEXERSERVICE']._serialized_start=342
  _globals['_INDEXERSERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
