# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: searcher.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esearcher.proto\x12\x08searcher\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\xa7\x01\n\x0cSearchResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x11\n\tsource_id\x18\x03 \x01(\t\x12\x36\n\x08metadata\x18\x04 \x03(\x0b\x32$.searcher.SearchResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"N\n\x0eSearchResponse\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.searcher.SearchResult\x12\x13\n\x0bsearch_time\x18\x02 \x01(\x01\x32N\n\x0fSearcherService\x12;\n\x06Search\x12\x17.searcher.SearchRequest\x1a\x18.searcher.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'searcher_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=28
  _globals['_SEARCHREQUEST']._serialized_end=58
  _globals['_SEARCHRESULT']._serialized_start=61
  _globals['_SEARCHRESULT']._serialized_end=228
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_start=181
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_end=228
  _globals['_SEARCHRESPONSE']._serialized_start=230
  _globals['_SEARCHRESPONSE']._serialized_end=308
  _globals['_SEARCHERSERVICE']._serialized_start=310
  _globals['_SEARCHERSERVICE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
