# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgenerator.proto\x12\tgenerator\"j\n\x11GenerationRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12/\n\x0esearch_results\x18\x02 \x03(\x0b\x32\x17.generator.SearchResult\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\"\xa8\x01\n\x0cSearchResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x11\n\tsource_id\x18\x03 \x01(\t\x12\x37\n\x08metadata\x18\x04 \x03(\x0b\x32%.generator.SearchResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"N\n\x12GenerationResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07sources\x18\x02 \x03(\t\x12\x17\n\x0fgeneration_time\x18\x03 \x01(\x01\x32[\n\x10GeneratorService\x12G\n\x08Generate\x12\x1c.generator.GenerationRequest\x1a\x1d.generator.GenerationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_GENERATIONREQUEST']._serialized_start=30
  _globals['_GENERATIONREQUEST']._serialized_end=136
  _globals['_SEARCHRESULT']._serialized_start=139
  _globals['_SEARCHRESULT']._serialized_end=307
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_start=260
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_end=307
  _globals['_GENERATIONRESPONSE']._serialized_start=309
  _globals['_GENERATIONRESPONSE']._serialized_end=387
  _globals['_GENERATORSERVICE']._serialized_start=389
  _globals['_GENERATORSERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
