# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generator_pb2 as generator__pb2


class GeneratorServiceStub(object):
    """Сервис генерации ответов
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/generator.GeneratorService/Generate',
                request_serializer=generator__pb2.GenerationRequest.SerializeToString,
                response_deserializer=generator__pb2.GenerationResponse.FromString,
                )


class GeneratorServiceServicer(object):
    """Сервис генерации ответов
    """

    def Generate(self, request, context):
        """Метод для генерации ответа на основе поисковой выдачи
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=generator__pb2.GenerationRequest.FromString,
                    response_serializer=generator__pb2.GenerationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generator.GeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GeneratorService(object):
    """Сервис генерации ответов
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/generator.GeneratorService/Generate',
            generator__pb2.GenerationRequest.SerializeToString,
            generator__pb2.GenerationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
