# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedder.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mbedder.proto\x12\x08\x65mbedder\"\x19\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1b\n\nTextChunks\x12\r\n\x05texts\x18\x01 \x03(\t\"!\n\x0f\x45mbeddingVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\">\n\x10\x45mbeddingVectors\x12*\n\x07vectors\x18\x01 \x03(\x0b\x32\x19.embedder.EmbeddingVector2\x94\x01\n\x0f\x45mbedderService\x12>\n\x0cGetEmbedding\x12\x13.embedder.TextChunk\x1a\x19.embedder.EmbeddingVector\x12\x41\n\rGetEmbeddings\x12\x14.embedder.TextChunks\x1a\x1a.embedder.EmbeddingVectorsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedder_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEXTCHUNK']._serialized_start=28
  _globals['_TEXTCHUNK']._serialized_end=53
  _globals['_TEXTCHUNKS']._serialized_start=55
  _globals['_TEXTCHUNKS']._serialized_end=82
  _globals['_EMBEDDINGVECTOR']._serialized_start=84
  _globals['_EMBEDDINGVECTOR']._serialized_end=117
  _globals['_EMBEDDINGVECTORS']._serialized_start=119
  _globals['_EMBEDDINGVECTORS']._serialized_end=181
  _globals['_EMBEDDERSERVICE']._serialized_start=184
  _globals['_EMBEDDERSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
